version: "3.7"
services:
  docker-fastapi:
    container_name: backend
    image: ghcr.io/jlake310/frontend_image
    restart: always
    networks:
      - chosen-network

  nginx:
    depends_on:
      - docker-fastapi
    container_name: frontend
    image: ghcr.io/jlake310/backend_image
    ports:
      - "80:80"
    restart: always
    networks:
      - chosen-network

networks:
  chosen-network:
    driver: bridge
